#+title: Монорепозиторий Neurography вуб сервисов

** Структура репозитория
  В репозитории хранится код всех сервисов Neurography в соответствующих директориях.

  | Директория | Описание                       |
  |------------+--------------------------------|
  | =/docs=      | Общая документация по сервисам |
  | =/common=    | Общее для всех сервисов        |
  | =/frontend=  | Основной сервис frontend       |

** Docker
*** dev
    При необходимости создайте =docker-compose.override.yml=,
    =docker-compose.development.override.yml=, если необходимы настройки
    под вашу машину для соотвествующей сборки.

    #+begin_src bash
      # Собрать образы
      $ make build

      # Поднять мир
      $ make up
    #+end_src

    Почти для каждой команды можно указать аргумет =c=foo=, чтобы она
    работала только с сервисом =foo=, например =make up backend= поднимет
    только =backend=.

    Теперь для проверки можно зайти на =http://localhost=.

    Если на вашем компьютере работает несколько серверов, можно в
    =docker-compose.development.override.yml= указать.

    #+begin_src yaml
      services:
        gateway:
          build:
            args:
              server_name: skillcity.local # сервер будет доступен только для http://skillcity.local
          ports:
            - 8080:80 # сервер будет доступен на порту 8080 вместо 80
    #+end_src

    Для достуа по отдельному домену добавьте его в системный =hosts=.

    Необходимо также развернуть схемы базы данных. Выполняется через
    Adminer (инструкцию по запуску см. ниже).
    
*** Утилиты

**** Adminer
    Для запуска Adminer:
    #+begin_src bash
      $ make up c=adminer
    #+end_src
